#version 430

#include "utils.include"

layout (local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

layout(set = 0, binding = 0, rgba16) uniform image2D images[2];

const float fov = 70.f;

layout(set = 0, binding = 1) uniform UBO{
    mat4 projInv;
    mat4 viewInv;
    ivec2 imageSize;
} ubo;

layout(std430, push_constant) uniform Pc{
    int frameNumber;
}pc ;



void main(){

    const vec3 tri[3] = vec3[](vec3(0,1, -20), vec3(-1,-1, 0), vec3(1, -1, 0) ); 

    ivec2 imageSize = ubo.imageSize;
    ivec2 id = ivec2(gl_GlobalInvocationID.xy);

    vec2 ndc;

    ndc.x =  float(id.x) / imageSize.x * 2 - 1;
    ndc.y =  float(imageSize.y -id.y) / imageSize.y * 2 - 1;

    vec4 world = ubo.viewInv * ubo.projInv* vec4(ndc, 1.0, 1.0);
    vec3 posOnPlane = world.xyz / world.w;

    vec3 cameraPos = ubo.viewInv[3].xyz;

    vec3 rayDir = normalize(posOnPlane - cameraPos);
    Ray ray;
    ray.origin = cameraPos;
    ray.direction = rayDir;
    float t, u, v;

    if(intersectTriangle(ray, tri[0], tri[1], tri[2], t, u, v)){
        vec4 color = vec4(sin(t * 10.0));
        imageStore(images[0], id, color);
        return;
    }
    imageStore(images[0], id, vec4(0));
}